# Generated by Django 6.1.1 on 2026-09-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='RoundChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_round_chores', to='chores.householdmember')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_round_chores', to='chores.householdmember')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_chores', to='chores.chore')),
                ('weekly_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_chores', to='chores.weeklyround')),
            ],
            options={
                'ordering': ['chore__name'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_confirmations', to='chores.householdmember')),
                ('weekly_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_confirmations', to='chores.weeklyround')),
            ],
        ),
        migrations.CreateModel(
            name='ChoreSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('first', 'First allocation round'), ('second', 'Second allocation round')], max_length=6)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chore_selections', to='chores.householdmember')),
                ('round_chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='chores.roundchore')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round_chore', 'member', 'phase'), name='unique_chore_selection_per_member_and_phase')],
            },
        ),
        migrations.AddConstraint(
            model_name='roundchore',
            constraint=models.UniqueConstraint(fields=('weekly_round', 'chore'), name='unique_chore_per_weekly_round'),
        ),
        migrations.AddConstraint(
            model_name='roundchore',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_to__isnull', True), ('status', 'pending')), models.Q(('assigned_to__isnull', False), ('status', 'assigned')), models.Q(('assigned_to__isnull', False), ('status', 'completed')), _connector='OR'), name='round_chore_status_matches_assignment'),
        ),
        migrations.AddConstraint(
            model_name='readinessconfirmation',
            constraint=models.UniqueConstraint(fields=('weekly_round', 'member'), name='unique_readiness_confirmation_per_member_and_round'),
        ),
    ]
